"""Removed ministry enum

Revision ID: f115d8bcc2e0
Revises: cbddfc2c434b
Create Date: 2021-03-15 16:42:45.523560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f115d8bcc2e0'
down_revision = 'cbddfc2c434b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExpenseReport', sa.Column('ministryID', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_ExpenseReport_ministryID_Ministries'), 'ExpenseReport', 'Ministries', ['ministryID'], ['id'])
    op.drop_column('ExpenseReport', 'ministry')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExpenseReport', sa.Column('ministry', mysql.ENUM('children', 'hiC', 'youngPeople'), nullable=False))
    op.drop_constraint(op.f('fk_ExpenseReport_ministryID_Ministries'), 'ExpenseReport', type_='foreignkey')
    op.drop_column('ExpenseReport', 'ministryID')
    # ### end Alembic commands ###
