"""Nullable for Categories.remark must be True

Revision ID: aaa0d63681c9
Revises: c0c410091c59
Create Date: 2021-03-16 13:45:55.573236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aaa0d63681c9'
down_revision = 'c0c410091c59'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Categories', 'remarks',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Categories', 'remarks',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
