"""with roles column

Revision ID: 7262a55f098d
Revises: d1b294e2afd7
Create Date: 2021-03-09 01:00:15.282677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7262a55f098d'
down_revision = 'd1b294e2afd7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('member', 'headOfDepartment', 'headOfDepartmentOfFinance', 'elderOfDepartmentOfFinance', 'siteAdmin', name='userrolesenum'), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
