"""changed detailedReport to detailedReports

Revision ID: 20f1d6eef87b
Revises: aaa0d63681c9
Create Date: 2021-03-18 21:13:22.199560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20f1d6eef87b'
down_revision = 'aaa0d63681c9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DetailedReports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('formID', sa.Integer(), nullable=False),
    sa.Column('categoryID', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amountSpent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('breakdown', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['categoryID'], ['Categories.id'], name=op.f('fk_DetailedReports_categoryID_Categories')),
    sa.ForeignKeyConstraint(['formID'], ['ExpenseReport.id'], name=op.f('fk_DetailedReports_formID_ExpenseReport')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_DetailedReports'))
    )
    op.drop_table('DetailedReport')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DetailedReport',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('formID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categoryID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('amountSpent', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('breakdown', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['categoryID'], ['Categories.id'], name='fk_DetailedReport_categoryID_Categories'),
    sa.ForeignKeyConstraint(['formID'], ['ExpenseReport.id'], name='fk_DetailedReport_formID_ExpenseReport'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('DetailedReports')
    # ### end Alembic commands ###
