"""fixed typo on ExpenseReport models

Revision ID: e891b1f76d92
Revises: 1cfe05489941
Create Date: 2021-03-15 18:06:41.045724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e891b1f76d92'
down_revision = '1cfe05489941'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExpenseReport', sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.drop_column('ExpenseReport', 'amountSpent')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExpenseReport', sa.Column('amountSpent', mysql.DECIMAL(precision=12, scale=2), nullable=False))
    op.drop_column('ExpenseReport', 'amount')
    # ### end Alembic commands ###
