"""changed ExpenseReport.ministry to ExpenseReport.ministryID

Revision ID: beadd54fd4ff
Revises: f115d8bcc2e0
Create Date: 2021-03-15 16:43:37.587658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beadd54fd4ff'
down_revision = 'f115d8bcc2e0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
