"""With expense report tables

Revision ID: c7e7c9a1aecb
Revises: e5b5d6b996b8
Create Date: 2021-03-14 03:05:21.191122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e7c9a1aecb'
down_revision = 'e5b5d6b996b8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lastKorName', sa.Text(), nullable=False),
    sa.Column('firstKorName', sa.Text(), nullable=False),
    sa.Column('lastLegalName', sa.Text(), nullable=False),
    sa.Column('firstLegalName', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=350), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('member', 'headOfDepartment', 'headOfDepartmentOfFinance', 'elderOfDepartmentOfFinance', 'siteAdmin', name='userrolesenum'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_User')),
    sa.UniqueConstraint('email', name=op.f('uq_User_email'))
    )
    op.create_index('email_index', 'User', ['email'], unique=True, mysql_length=320)
    op.create_table('ExpenseReport',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('ministry', sa.Enum('children', 'hiC', 'youngPeople', name='ministries'), nullable=False),
    sa.Column('korName', sa.Text(), nullable=False),
    sa.Column('legalName', sa.Text(), nullable=False),
    sa.Column('amountSpent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['User.id'], name=op.f('fk_ExpenseReport_userID_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ExpenseReport'))
    )
    op.create_table('Categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('formID', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('amountSpent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['formID'], ['ExpenseReport.id'], name=op.f('fk_Categories_formID_ExpenseReport')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Categories'))
    )
    op.create_table('ReportApproval',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('formID', sa.Integer(), nullable=False),
    sa.Column('headOfDepartment', sa.Boolean(), nullable=False),
    sa.Column('headOfFinancial', sa.Boolean(), nullable=False),
    sa.Column('financialElder', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['formID'], ['ExpenseReport.id'], name=op.f('fk_ReportApproval_formID_ExpenseReport')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ReportApproval'))
    )
    op.create_table('DetailedReport',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('formID', sa.Integer(), nullable=False),
    sa.Column('categoryID', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amountSpent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('breakdown', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['categoryID'], ['Categories.id'], name=op.f('fk_DetailedReport_categoryID_Categories')),
    sa.ForeignKeyConstraint(['formID'], ['ExpenseReport.id'], name=op.f('fk_DetailedReport_formID_ExpenseReport')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_DetailedReport'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DetailedReport')
    op.drop_table('ReportApproval')
    op.drop_table('Categories')
    op.drop_table('ExpenseReport')
    op.drop_index('email_index', table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
