"""Names are dividede into two columns

Revision ID: d1b294e2afd7
Revises: c6bcde008c30
Create Date: 2021-03-06 17:36:36.662511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1b294e2afd7'
down_revision = 'c6bcde008c30'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstKorName', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('firstLegalName', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('lastKorName', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('lastLegalName', sa.Text(), nullable=False))
    op.drop_index('ix_user_email', table_name='user')
    op.create_index('email_index', 'user', ['email'], unique=True, mysql_length=320)
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    op.drop_column('user', 'korName')
    op.drop_column('user', 'legalName')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('legalName', mysql.TEXT(), nullable=False))
    op.add_column('user', sa.Column('korName', mysql.TEXT(), nullable=False))
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    op.drop_index('email_index', table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_column('user', 'lastLegalName')
    op.drop_column('user', 'lastKorName')
    op.drop_column('user', 'firstLegalName')
    op.drop_column('user', 'firstKorName')
    # ### end Alembic commands ###
