"""changed ExpenseReport now automatically adds date

Revision ID: 1cfe05489941
Revises: beadd54fd4ff
Create Date: 2021-03-15 16:49:05.844929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cfe05489941'
down_revision = 'beadd54fd4ff'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExpenseReport', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ExpenseReport', 'date')
    # ### end Alembic commands ###
